TRAIN_CONFIG:
    TEST_RUN: True
    MODEL: "VIT"
    MODEL_PARAMS:
        NUM_LAYERS: 1
        EMBEDDING_SIZE: 32
        NUM_HEADS: 1
        PATCH_SIZE: 8
        T_THRESHOLD: 1
        NUM_CLS: 1
    OPTIMIZER: "AdamW"
    OPTIMIZER_PARAMS:
        LR: 0.0002
        NUM_EPOCHS: 1500
        LR_SCHEDULER: "None"
    LOSS_FN: "CrossEntropyLoss"
    TRAINER: "BaseTrainer"
    TRAINER_PARAMS:
        LOG_INTERVAL: 4
        VAL_INTERVAL: 1
        DATA_PARALLEL: [False]
    DATA_LOADER: "Image_Dataloader"
    DATA_LOADER_PARAMS:
        DATASET_NAME: "CIFAR10" # Options: ["ImageNet", "CIFAR10", "CIFAR100", "MNIST", "FashionMNIST"]
        DATA_DIR: "data"
        BATCH_SIZE: 2
        NUM_WORKERS: 1
    WANDB_LOGGING_PARAMS:
        PROJECT: "template_test"
        DIR: "TEMPLATE/log"
    EARLY_STOPPING_PARAMS:
        PATIENCE: 10000
        DELTA: 0.001
        VERBOSE: False