TRAIN_CONFIG:
    TEST_RUN: True
    MODEL: "ImageTreensformerV6"
    MODEL_PARAMS:
        NUM_LAYERS: 2
        EMBEDDING_SIZE: 18
        NUM_HEADS: 2
        PATCH_SIZE: 8
        T_THRESHOLD: 0
        NUM_CLS: 1
        H_REG: 0
        MASK:
            PARENT_CHILD: True
            CHILD_PARENT: False
            SIBLING: True
            COUSIN: True
            GRANDPARENT_GRANDCHILD: True
            GRANDCHILD_GRANDPARENT: False
        MLP:
          HIDDEN_MULTIPLIER: 4

    OPTIMIZER: "AdamW"
    OPTIMIZER_PARAMS:
        LR: 0.002
        NUM_EPOCHS: 4
        LR_SCHEDULER: "None"
    LOSS_FN: "CrossEntropyLoss"
    TRAINER: "BaseTrainer"
    TRAINER_PARAMS:
        LOG_INTERVAL: 4
        VAL_INTERVAL: 1
        DATA_PARALLEL: False
    DATA_LOADER: "Image_Dataloader"
    DATA_LOADER_PARAMS:
        DATASET_NAME: "CIFAR100" # Options: ["ImageNet", "CIFAR10", "CIFAR100", "MNIST", "FashionMNIST"]
        DATA_DIR: "data"
        BATCH_SIZE: 1
        NUM_WORKERS: 4
        AUGMENTATION: True
    WANDB_LOGGING_PARAMS:
        PROJECT: "Treensformer"
        DIR: "TEMPLATE/log"
        NOTES: "Shared branch MLP"
    EARLY_STOPPING_PARAMS:
        PATIENCE: 800
        DELTA: 0.0001
        VERBOSE: False

    COMPILATION:
        MODE: "default" # Options: ["default", "full", "reduce-overhead"]
    EMIT_NVTX: TRUE