

program: TEMPLATE/main.py
method: random
metric:
  name: validation_loss
  goal: minimize
parameters:
  TEST_RUN:
    values: [False]
  MODEL:
    values: ["ImageTreensformer"]
      
  MODEL_PARAMS:
    parameters:
      NUM_LAYERS:
        values: [4]
      EMBEDDING_SIZE:
        values: [16]
      NUM_HEADS:
        values: [4]
      PATCH_SIZE: 
        values: [2]
      T_THRESHOLD:
        values: [0]
      NUM_CLS:
        values: [1]

  OPTIMIZER: 
      values: ["AdamW"]

  OPTIMIZER_PARAMS:
    parameters:
      LR:
        values: [0.0001]
      NUM_EPOCHS:
        values: [80]
      LR_SCHEDULER:
        values: ["CosineAnnealingLR"]

  LOSS_FN: 
      values: ["CrossEntropyLoss"]

  TRAINER: 
      values: ["BaseTrainer"]
  TRAINER_PARAMS:
    parameters:
      LOG_INTERVAL:
        values: [20]
      VAL_INTERVAL:
        values: [1]
      DATA_PARALLEL:
        values: [False]

  DATA_LOADER: 
      values: ["Image_Dataloader"]

  DATA_LOADER_PARAMS:
    parameters:
      DATASET_NAME:
        values: ["CIFAR100"]
      DATA_DIR:
        values: ["data"]
      BATCH_SIZE:
        values: [16]
      NUM_WORKERS: 
        values: [64]
      AUGMENTATION: 
        values: [True]





  
